import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-10 font-[family-name:var(--font-geist-sans)]">
          <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start h-[500px] bg-zinc-100x p-8 rounded-2xl">
            <div className="flex flex-row gap-6">
              <Image
                className="dark:invert"
                src="/next.svg"
                alt="Next.js logo"
                width={180}
                height={38}
                priority
              />

              <p className="text-5xl">+</p>
              <Image src="/open-next-logo.svg" alt="Open Next logo" width={200} height={50} />
              <p className="text-5xl">+</p>
              <Image src="/pulumi-logo.svg" alt="Pulumi logo" width={200} height={50} />
              <p className="text-5xl">+</p>
              <Image src="/aws-logo.svg" alt="AWS logo" width={100} height={40} />
            </div>
            {children}
          </main>
          <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
            <Link
              className="flex items-center gap-2 hover:underline hover:underline-offset-4"
              href="/"
              rel="noopener noreferrer"
            >
              ↩︎ Home
            </Link> | v1.0
          </footer>
        </div>
      </body>
    </html>
  );
}
