import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <header className="w-full py-8 px-8 sm:px-10 flex justify-center">
            <Header />
          </header>
          <div className="flex gap-4 items-center flex-col sm:flex-row justify-center">
            <Link
              className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:min-w-44"
              href="/fetching"
              rel="noopener noreferrer"
            >
              Fetching data from an external API
            </Link>
            <Link
              className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:min-w-44"
              href="/blog/1"
              rel="noopener noreferrer"
            >
              Incremental Static Regeneration (ISR) example
            </Link>
            <div>
              <Link
                className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:min-w-44"
                href="/api"
                rel="noopener noreferrer"
              >
                Route handler (API)
              </Link>
            </div>
          </div>
          <main className="flex-1 w-full px-8 pb-8 sm:px-10">
            <div className="h-full bg-zinc-100x p-8 rounded-2xl">
              {children}
            </div>
          </main>
          <footer className="w-full py-8 px-8 sm:px-10">
            <div className="flex gap-6 flex-wrap items-center justify-center">
              <Link
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="/"
                rel="noopener noreferrer"
              >
                ↩︎ Home
              </Link> | v1.2
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
